/**
 * Allegro Quantity Command Domain Entity
 *
 * Domain entity representing an Allegro offer quantity change command status.
 * Used for observability and debugging of quantity update operations.
 *
 * @module libs/integrations/allegro/src/domain/entities
 */
export const AllegroQuantityCommandStatusValues = [
  'queued',
  'accepted',
  'succeeded',
  'rejected',
  'failed',
] as const;

export type AllegroQuantityCommandStatus = (typeof AllegroQuantityCommandStatusValues)[number];

/**
 * Allegro Quantity Command Domain Entity
 */
export class AllegroQuantityCommand {
  constructor(
    public readonly id: string,
    public readonly commandId: string,
    public readonly connectionId: string,
    public readonly offerId: string,
    public readonly quantity: number,
    public readonly status: AllegroQuantityCommandStatus,
    public readonly error: string | null,
    public readonly createdAt: Date,
    public readonly updatedAt: Date,
  ) {}

  /**
   * Create a new command record
   */
  static create(
    commandId: string,
    connectionId: string,
    offerId: string,
    quantity: number,
    status: AllegroQuantityCommandStatus,
    error?: string | null,
  ): AllegroQuantityCommand {
    const now = new Date();
    return new AllegroQuantityCommand(
      '', // ID will be generated by repository
      commandId,
      connectionId,
      offerId,
      quantity,
      status,
      error || null,
      now,
      now,
    );
  }
}



