#!/bin/sh
# Rename the randomized admin folder generated by the PrestaShop 9.x installer
# to a deterministic name so the admin URL is stable across clean installs.
# See issue #156.
set -e

cd /var/www/html

TARGET="admin-dev"

if [ -d "$TARGET" ]; then
    echo "* $TARGET already present, nothing to rename"
    exit 0
fi

RANDOM_ADMIN=$(ls -d admin[0-9a-z]* 2>/dev/null | grep -v '^admin-api$' | head -1 || true)

if [ -z "$RANDOM_ADMIN" ]; then
    echo "* No randomized admin folder found, skipping rename"
    exit 0
fi

mv "$RANDOM_ADMIN" "$TARGET"
echo "* Renamed $RANDOM_ADMIN → $TARGET"
