/**
 * Shipment Domain Entity
 *
 * Anemic readonly aggregate representing a single shipment attempt with a
 * shipping provider. Each row mirrors a real external commitment (one
 * `generateLabel` call → one provider shipment id → possibly one
 * paczkomat-locker reservation → possibly one carrier fee).
 *
 * Append-only multiplicity: 1 order → N shipments over time. The AC-7
 * "Cancel + re-issue" flow flips the existing row to `cancelled` and
 * inserts a new row for the re-issue. Preserves the cancelled tracking
 * number, paczkomat id, and label-pdf reference for audit + customer-
 * support forensics. Future multi-package shipments (spec §6 v2) drop
 * into the same schema without migration.
 *
 * Terminal-state timestamps (`dispatchedAt` / `deliveredAt` /
 * `cancelledAt` / `failedAt`) form an append-only timeline that can't be
 * overwritten by a later update — same shape as `OfferCreationRecord`.
 *
 * Identifier: `ol_shipment_<uuid-no-dashes>`, generated by the repository
 * at create-time via `formatInternalId('Shipment')`. Not cross-platform-
 * mapped — `IdentifierMappingService` is not involved.
 *
 * @module libs/core/src/shipping/domain/entities
 */

import type { ShipmentDirection } from '../types/shipment-direction.types';
import type { ShipmentStatus } from '../types/shipment-status.types';
import type { ShippingMethod } from '../types/shipping-method.types';
import type { DeliveryIntent } from '../types/delivery-intent.types';

export class Shipment {
  constructor(
    public readonly id: string,
    public readonly orderId: string,
    public readonly connectionId: string,
    public readonly shippingMethod: ShippingMethod,
    public readonly status: ShipmentStatus,
    public readonly providerShipmentId: string | null,
    public readonly paczkomatId: string | null,
    public readonly trackingNumber: string | null,
    public readonly labelPdfRef: string | null,
    public readonly dispatchedAt: Date | null,
    public readonly deliveredAt: Date | null,
    public readonly cancelledAt: Date | null,
    public readonly failedAt: Date | null,
    public readonly errorMessage: string | null,
    public readonly createdAt: Date,
    public readonly updatedAt: Date,
    // Deliberately appended AFTER the timestamps (not spliced among the
    // existing `string | null` fields) so a misplaced arg can't silently
    // reshuffle same-typed positions — the trailing slot is type-distinct from
    // the two `Date`s above, so omission/misplacement is a compile error.
    // Keep it here; do not "tidy" it into the middle. Required (no default) so
    // every construction site is forced to supply it.
    // Source marketplace delivery-method id this shipment was routed from
    // (audit/forensics; distinct from the resolved provider delivery method).
    public readonly sourceDeliveryMethodId: string | null,
    // Actual carrier-of-record (#769) — distinct from the dispatcher
    // (`connectionId.platformType`). For InPost own-contract always
    // `'inpost'`; for Allegro Delivery brokered shipments the carrier is
    // resolved from `transportingInfo[].carrierId` and arrives
    // asynchronously alongside the carrier waybill. Drives the FE's
    // public-tracker URL composition. Typed `string | null` to accept
    // plugin-registered values beyond the closed `KnownCarrierValues`
    // vocabulary (the FE gracefully degrades to copy-text for unknowns).
    // Once written, never overwritten — same backfill discipline as
    // `trackingNumber`. If a mid-flight carrier swap is ever needed
    // (rare), the operator workflow is cancel + re-issue.
    // Appended after `sourceDeliveryMethodId` for the same anti-collision
    // rationale as that field.
    public readonly carrier: string | null,
    // Carrier-neutral delivery intent the dispatch was requested with (#979,
    // ADR-020). `null` for branch-1/omp projection rows (no label, no intent).
    // The carrier-specific `shippingMethod` above is resolved from this at the
    // dispatch seam. Appended last for the same anti-collision rationale —
    // do not splice into the middle.
    public readonly deliveryIntent: DeliveryIntent | null,
    // Structured rejection-code discriminator (#1918) from the same
    // `ShippingProviderRejectionException` that produced `errorMessage` —
    // e.g. `preflight.missing-parcel-template`, `api.http-503`, or a
    // carrier-surfaced code. `null` when the failure carried no exception
    // (a plain `Error`) or the shipment never failed. Required (no default)
    // for the same anti-collision reason as `deliveryIntent`/`carrier` above.
    public readonly providerCode: string | null,
    // When the waybill was successfully relayed to the order's SOURCE
    // participant (#1947). This is a claim marker, not a timeline entry: the
    // carrier may mint the waybill only after the operator dispatched (ShipX
    // mints it at confirmation), so the source must be told on a later
    // tracking-backfill tick — and told exactly once.
    //
    // Why a dedicated column rather than inferring it from `trackingNumber`:
    // that field is the DATA, and it was previously doing double duty as the
    // retry marker for every participant. The overload made "delivered to the
    // source" and "known to OL" indistinguishable, so every retry re-drove the
    // source's non-idempotent waybill POST. Splitting the roles makes
    // at-most-once a database fact (claim `WHERE waybill_relayed_at IS NULL`)
    // and leaves `trackingNumber`'s destination-retry semantics untouched.
    //
    // Generalised per-destination notify state is #861; this single marker is
    // the first row of that model, not a competing half-measure.
    // Appended last for the same anti-collision rationale as the fields above.
    public readonly waybillRelayedAt: Date | null,
    // Which way the goods travel (#2373, ADR-060). `'outbound'` is the seller
    // shipping to a buyer — every row that existed before this field. A return
    // label shares the table because it IS a shipment (same carrier, same
    // waybill, same tracking poll), so the discriminator is what keeps the
    // branch-1 duplicate guard and every read predicate honest.
    //
    // Appended last for the same anti-collision rationale as the fields above
    // — do not splice it into the middle. Required (no default) so every
    // construction site is forced to state its cohort.
    public readonly direction: ShipmentDirection,
  ) {}
}
