/**
 * Shipment Domain Entity
 *
 * Anemic readonly aggregate representing a single shipment attempt with a
 * shipping provider. Each row mirrors a real external commitment (one
 * `generateLabel` call → one provider shipment id → possibly one
 * paczkomat-locker reservation → possibly one carrier fee).
 *
 * Append-only multiplicity: 1 order → N shipments over time. The AC-7
 * "Cancel + re-issue" flow flips the existing row to `cancelled` and
 * inserts a new row for the re-issue. Preserves the cancelled tracking
 * number, paczkomat id, and label-pdf reference for audit + customer-
 * support forensics. Future multi-package shipments (spec §6 v2) drop
 * into the same schema without migration.
 *
 * Terminal-state timestamps (`dispatchedAt` / `deliveredAt` /
 * `cancelledAt` / `failedAt`) form an append-only timeline that can't be
 * overwritten by a later update — same shape as `OfferCreationRecord`.
 *
 * Identifier: `ol_shipment_<uuid-no-dashes>`, generated by the repository
 * at create-time via `formatInternalId('Shipment')`. Not cross-platform-
 * mapped — `IdentifierMappingService` is not involved.
 *
 * @module libs/core/src/shipping/domain/entities
 */

import type { ShipmentStatus } from '../types/shipment-status.types';
import type { ShippingMethod } from '../types/shipping-method.types';

export class Shipment {
  constructor(
    public readonly id: string,
    public readonly orderId: string,
    public readonly connectionId: string,
    public readonly shippingMethod: ShippingMethod,
    public readonly status: ShipmentStatus,
    public readonly providerShipmentId: string | null,
    public readonly paczkomatId: string | null,
    public readonly trackingNumber: string | null,
    public readonly labelPdfRef: string | null,
    public readonly dispatchedAt: Date | null,
    public readonly deliveredAt: Date | null,
    public readonly cancelledAt: Date | null,
    public readonly failedAt: Date | null,
    public readonly errorMessage: string | null,
    public readonly createdAt: Date,
    public readonly updatedAt: Date,
    // Deliberately appended AFTER the timestamps (not spliced among the
    // existing `string | null` fields) so a misplaced arg can't silently
    // reshuffle same-typed positions — the trailing slot is type-distinct from
    // the two `Date`s above, so omission/misplacement is a compile error.
    // Keep it here; do not "tidy" it into the middle. Required (no default) so
    // every construction site is forced to supply it.
    // Source marketplace delivery-method id this shipment was routed from
    // (audit/forensics; distinct from the resolved provider delivery method).
    public readonly sourceDeliveryMethodId: string | null,
    // Actual carrier-of-record (#769) — distinct from the dispatcher
    // (`connectionId.platformType`). For InPost own-contract always
    // `'inpost'`; for Allegro Delivery brokered shipments the carrier is
    // resolved from `transportingInfo[].carrierId` and arrives
    // asynchronously alongside the carrier waybill. Drives the FE's
    // public-tracker URL composition. Typed `string | null` to accept
    // plugin-registered values beyond the closed `KnownCarrierValues`
    // vocabulary (the FE gracefully degrades to copy-text for unknowns).
    // Once written, never overwritten — same backfill discipline as
    // `trackingNumber`. If a mid-flight carrier swap is ever needed
    // (rare), the operator workflow is cancel + re-issue.
    // Appended after `sourceDeliveryMethodId` for the same anti-collision
    // rationale as that field.
    public readonly carrier: string | null,
  ) {}
}
