/**
 * Set Webhook Secret Request DTO
 *
 * Body for `PUT /connections/:id/webhooks/secret` (#1770) — a caller-supplied
 * webhook signing secret the operator copied from the external platform
 * (e.g. inFakt, which mints the secret itself and offers no API to accept
 * one). Distinct from the rotate flow, which generates a server-side value.
 *
 * @module apps/api/src/integrations/http/dto
 */
import { ApiProperty } from '@nestjs/swagger';
import { IsNotEmpty, IsString, MaxLength, MinLength } from 'class-validator';

export class SetWebhookSecretDto {
  @ApiProperty({
    description: 'The webhook signing secret generated by the external platform.',
    minLength: 8,
    maxLength: 512,
  })
  @IsString()
  @IsNotEmpty()
  @MinLength(8)
  @MaxLength(512)
  secret!: string;
}
