/**
 * Order Processor Types
 *
 * Type definitions for order processor operations. Defines order creation
 * requests and references used by OrderProcessorManagerPort.
 *
 * This file contains types only (per engineering standards).
 *
 * @module libs/core/src/orders/domain/types
 */
import {
  OrderItem,
  OrderTotals,
  Address,
  OrderShipping,
  OrderPickupPoint,
} from '../types/order.types';
import { OrderStatus } from './order.types';

/**
 * Source reference for an order being created on a destination platform.
 *
 * Distinct from `OrderSourcePort` (the capability port that ingests orders
 * from a source) — this is a passive metadata tag attached to `OrderCreate`
 * so destination adapters can call back into source-scoped resources
 * (e.g. resolving a carrier mapping keyed by the source `methodId`).
 */
export interface OrderSourceRef {
  connectionId: string;
  eventId?: string;
}

/**
 * Order creation request
 *
 * Represents a request to create an order in an external system.
 * All identifiers should be internal OpenLinker IDs. The adapter is responsible
 * for mapping internal IDs to external IDs using IdentifierMappingService.
 */
export interface OrderCreate {
  /**
   * Order number (optional, may be generated by the destination system)
   */
  orderNumber?: string;

  /**
   * Order status
   */
  status: OrderStatus;

  /**
   * Customer ID (internal OpenLinker ID)
   */
  customerId?: string;

  /**
   * Order line items
   */
  items: OrderItem[];

  /**
   * Order totals
   */
  totals: OrderTotals;

  /**
   * Shipping address
   */
  shippingAddress?: Address;

  /**
   * Billing address
   */
  billingAddress?: Address;

  /**
   * Source-side shipping reference (e.g. Allegro `delivery.method`). Carrier
   * resolution at the destination adapter consumes `methodId`. Optional —
   * order sources that don't expose a delivery-method id leave it undefined.
   */
  shipping?: OrderShipping;

  /**
   * Pickup-point reference (locker etc.). Present only for pickup-point orders.
   */
  pickupPoint?: OrderPickupPoint;

  /**
   * Reference to the source connection / event this order was ingested from.
   * Used by destination adapters to look up source-scoped configuration
   * (e.g. carrier mappings keyed by the source `methodId`).
   */
  source?: OrderSourceRef;

  /**
   * Optional metadata for the order
   */
  metadata?: Record<string, unknown>;
}

/**
 * Order reference
 *
 * Represents a reference to a created order. Contains the order ID
 * (which may be internal or external depending on the adapter's return value)
 * and optional order number.
 */
export interface OrderRef {
  /**
   * Order identifier (may be internal OpenLinker ID or external platform ID)
   */
  orderId: string;

  /**
   * Order number (if available)
   */
  orderNumber?: string;
}

