/**
 * Order Processor Types
 *
 * Type definitions for order processor operations. Defines order creation
 * requests and references used by OrderProcessorManagerPort.
 *
 * This file contains types only (per engineering standards).
 *
 * @module libs/core/src/orders/domain/types
 */
import { OrderItem, OrderTotals, Address } from '../ports/order-source.port';
import { OrderStatus } from './order.types';

/**
 * Order creation request
 *
 * Represents a request to create an order in an external system.
 * All identifiers should be internal OpenLinker IDs. The adapter is responsible
 * for mapping internal IDs to external IDs using IdentifierMappingService.
 */
export interface OrderCreate {
  /**
   * Order number (optional, may be generated by the destination system)
   */
  orderNumber?: string;

  /**
   * Order status
   */
  status: OrderStatus;

  /**
   * Customer ID (internal OpenLinker ID)
   */
  customerId?: string;

  /**
   * Order line items
   */
  items: OrderItem[];

  /**
   * Order totals
   */
  totals: OrderTotals;

  /**
   * Shipping address
   */
  shippingAddress?: Address;

  /**
   * Billing address
   */
  billingAddress?: Address;

  /**
   * Optional metadata for the order
   */
  metadata?: Record<string, unknown>;
}

/**
 * Order reference
 *
 * Represents a reference to a created order. Contains the order ID
 * (which may be internal or external depending on the adapter's return value)
 * and optional order number.
 */
export interface OrderRef {
  /**
   * Order identifier (may be internal OpenLinker ID or external platform ID)
   */
  orderId: string;

  /**
   * Order number (if available)
   */
  orderNumber?: string;
}

