import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Migration: Change Product/Variant/Inventory ID columns from UUID to TEXT
 *
 * This migration changes canonical entity IDs (Product, ProductVariant, InventoryItem)
 * from UUID to TEXT to align with the internal ID format generated by IdentifierMappingService
 * (format: ol_{entityType}_{uuid}).
 *
 * Important notes:
 * - Uses TEXT instead of VARCHAR for consistency (PostgreSQL treats them identically)
 * - Includes partial unique indexes for inventory_items to prevent duplicate base/variant rows
 * - If any data exists, UUID values will be cast to strings but won't match ol_* format
 *   (assumes dev-only/empty tables - if production data exists, need transformation strategy)
 */
export class ChangeProductIdsToVarchar1767555200000 implements MigrationInterface {
  name = 'ChangeProductIdsToVarchar1767555200000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // Drop foreign key constraints first
    await queryRunner.query(
      `ALTER TABLE "inventory_items" DROP CONSTRAINT IF EXISTS "FK_8fa4cdd8e98fde93d4f14025417"`,
    );
    await queryRunner.query(
      `ALTER TABLE "inventory_items" DROP CONSTRAINT IF EXISTS "FK_4a1e232a660d7d51a13f20099b2"`,
    );
    await queryRunner.query(
      `ALTER TABLE "product_variants" DROP CONSTRAINT IF EXISTS "FK_f515690c571a03400a9876600b5"`,
    );

    // Drop existing indexes (will recreate with correct types)
    await queryRunner.query(
      `DROP INDEX IF EXISTS "IDX_c8aa42e2481ff1992bca22a9bc"`,
    );
    await queryRunner.query(
      `DROP INDEX IF EXISTS "IDX_b907bd3ca244348f00e235a3f8"`,
    );

    // Change products.id from uuid to text
    await queryRunner.query(
      `ALTER TABLE "products" ALTER COLUMN "id" TYPE text USING id::text`,
    );
    await queryRunner.query(
      `ALTER TABLE "products" ALTER COLUMN "id" DROP DEFAULT`,
    );

    // Change product_variants.id from uuid to text
    await queryRunner.query(
      `ALTER TABLE "product_variants" ALTER COLUMN "id" TYPE text USING id::text`,
    );
    await queryRunner.query(
      `ALTER TABLE "product_variants" ALTER COLUMN "id" DROP DEFAULT`,
    );

    // Change product_variants.productId from uuid to text
    await queryRunner.query(
      `ALTER TABLE "product_variants" ALTER COLUMN "productId" TYPE text USING "productId"::text`,
    );

    // Change inventory_items.id from uuid to text
    await queryRunner.query(
      `ALTER TABLE "inventory_items" ALTER COLUMN "id" TYPE text USING id::text`,
    );
    await queryRunner.query(
      `ALTER TABLE "inventory_items" ALTER COLUMN "id" DROP DEFAULT`,
    );

    // Change inventory_items.productId from uuid to text
    await queryRunner.query(
      `ALTER TABLE "inventory_items" ALTER COLUMN "productId" TYPE text USING "productId"::text`,
    );

    // Change inventory_items.productVariantId from uuid to text
    await queryRunner.query(
      `ALTER TABLE "inventory_items" ALTER COLUMN "productVariantId" TYPE text USING "productVariantId"::text`,
    );

    // Recreate foreign key constraints
    await queryRunner.query(
      `ALTER TABLE "product_variants" ADD CONSTRAINT "FK_f515690c571a03400a9876600b5" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "inventory_items" ADD CONSTRAINT "FK_4a1e232a660d7d51a13f20099b2" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "inventory_items" ADD CONSTRAINT "FK_8fa4cdd8e98fde93d4f14025417" FOREIGN KEY ("productVariantId") REFERENCES "product_variants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );

    // Recreate partial unique indexes for inventory_items
    // Critical: Prevents duplicate base inventory rows when productVariantId is NULL
    await queryRunner.query(
      `CREATE UNIQUE INDEX "IDX_inventory_items_product_base_unique" ON "inventory_items" ("productId", "locationId") WHERE "productVariantId" IS NULL`,
    );
    // Prevents duplicate variant inventory rows when productVariantId is NOT NULL
    await queryRunner.query(
      `CREATE UNIQUE INDEX "IDX_inventory_items_product_variant_unique" ON "inventory_items" ("productId", "productVariantId", "locationId") WHERE "productVariantId" IS NOT NULL`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Drop partial unique indexes
    await queryRunner.query(
      `DROP INDEX IF EXISTS "IDX_inventory_items_product_variant_unique"`,
    );
    await queryRunner.query(
      `DROP INDEX IF EXISTS "IDX_inventory_items_product_base_unique"`,
    );

    // Drop foreign key constraints
    await queryRunner.query(
      `ALTER TABLE "inventory_items" DROP CONSTRAINT IF EXISTS "FK_8fa4cdd8e98fde93d4f14025417"`,
    );
    await queryRunner.query(
      `ALTER TABLE "inventory_items" DROP CONSTRAINT IF EXISTS "FK_4a1e232a660d7d51a13f20099b2"`,
    );
    await queryRunner.query(
      `ALTER TABLE "product_variants" DROP CONSTRAINT IF EXISTS "FK_f515690c571a03400a9876600b5"`,
    );

    // Revert inventory_items.productVariantId to uuid
    // Note: This will fail if any IDs don't match UUID format (e.g., ol_* format)
    await queryRunner.query(
      `ALTER TABLE "inventory_items" ALTER COLUMN "productVariantId" TYPE uuid USING "productVariantId"::uuid`,
    );

    // Revert inventory_items.productId to uuid
    await queryRunner.query(
      `ALTER TABLE "inventory_items" ALTER COLUMN "productId" TYPE uuid USING "productId"::uuid`,
    );

    // Revert inventory_items.id to uuid
    await queryRunner.query(
      `ALTER TABLE "inventory_items" ALTER COLUMN "id" TYPE uuid USING id::uuid`,
    );
    await queryRunner.query(
      `ALTER TABLE "inventory_items" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`,
    );

    // Revert product_variants.productId to uuid
    await queryRunner.query(
      `ALTER TABLE "product_variants" ALTER COLUMN "productId" TYPE uuid USING "productId"::uuid`,
    );

    // Revert product_variants.id to uuid
    await queryRunner.query(
      `ALTER TABLE "product_variants" ALTER COLUMN "id" TYPE uuid USING id::uuid`,
    );
    await queryRunner.query(
      `ALTER TABLE "product_variants" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`,
    );

    // Revert products.id to uuid
    await queryRunner.query(
      `ALTER TABLE "products" ALTER COLUMN "id" TYPE uuid USING id::uuid`,
    );
    await queryRunner.query(
      `ALTER TABLE "products" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`,
    );

    // Recreate foreign key constraints
    await queryRunner.query(
      `ALTER TABLE "product_variants" ADD CONSTRAINT "FK_f515690c571a03400a9876600b5" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "inventory_items" ADD CONSTRAINT "FK_4a1e232a660d7d51a13f20099b2" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "inventory_items" ADD CONSTRAINT "FK_8fa4cdd8e98fde93d4f14025417" FOREIGN KEY ("productVariantId") REFERENCES "product_variants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );

    // Recreate original indexes (from initial migration)
    await queryRunner.query(
      `CREATE UNIQUE INDEX "IDX_c8aa42e2481ff1992bca22a9bc" ON "inventory_items" ("productId", "productVariantId", "locationId") WHERE "productVariantId" IS NOT NULL`,
    );
    await queryRunner.query(
      `CREATE UNIQUE INDEX "IDX_b907bd3ca244348f00e235a3f8" ON "inventory_items" ("productId", "locationId") WHERE "productVariantId" IS NULL`,
    );
  }
}

