/**
 * Add shipments table (#763)
 *
 * Foundation slice for the InPost shipping epic (#727). Creates the
 * `shipments` table that mirrors each `generateLabel` attempt against a
 * shipping provider (one provider shipment id per row, append-only).
 *
 * Schema notes:
 * - `id` is `text` (not `uuid`): generated by the application via
 *   `formatInternalId('Shipment')` → `ol_shipment_<uuid-no-dashes>`,
 *   matching the canonical OL internal-ID format for first-class business
 *   aggregates.
 * - `orderId` is `text` to match the `ol_order_*` shape persisted on the
 *   orders table.
 * - `connectionId` is `uuid` (connections are stored with `gen_random_uuid()`).
 * - Multiple rows per `orderId` are allowed by design (AC-7 cancel +
 *   re-issue, future multi-package shipments) — the orderId index is
 *   non-unique. A partial-unique index on `providerShipmentId` (where it
 *   is non-null) prevents two rows ever claiming the same external id.
 * - No FK constraints emitted (matches recent `bulk_offer_creation_batches`
 *   convention; cross-context FKs add migration coupling).
 *
 * @module apps/api/src/migrations
 */
import type { MigrationInterface, QueryRunner } from 'typeorm';

export class AddShipmentsTable1799000000000 implements MigrationInterface {
  name = 'AddShipmentsTable1799000000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "shipments" (
        "id"                  text PRIMARY KEY,
        "orderId"             text NOT NULL,
        "connectionId"        uuid NOT NULL,
        "shippingMethod"      text NOT NULL,
        "status"              text NOT NULL,
        "providerShipmentId"  text,
        "paczkomatId"         text,
        "trackingNumber"      text,
        "labelPdfRef"         text,
        "dispatchedAt"        TIMESTAMP,
        "deliveredAt"         TIMESTAMP,
        "cancelledAt"         TIMESTAMP,
        "failedAt"            TIMESTAMP,
        "errorMessage"        text,
        "createdAt"           TIMESTAMP NOT NULL DEFAULT now(),
        "updatedAt"           TIMESTAMP NOT NULL DEFAULT now()
      )
    `);
    await queryRunner.query(
      `CREATE INDEX "IDX_shipments_orderId" ON "shipments" ("orderId")`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_shipments_connectionId" ON "shipments" ("connectionId")`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_shipments_status" ON "shipments" ("status")`,
    );
    await queryRunner.query(
      `CREATE UNIQUE INDEX "UQ_shipments_providerShipmentId" ON "shipments" ("providerShipmentId") WHERE "providerShipmentId" IS NOT NULL`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Indexes on the dropped table are removed implicitly by DROP TABLE,
    // but dropping them explicitly first keeps the rollback safe even if
    // the table fails to drop for any reason (FKs from a future migration,
    // …).
    await queryRunner.query(`DROP INDEX IF EXISTS "UQ_shipments_providerShipmentId"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "IDX_shipments_status"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "IDX_shipments_connectionId"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "IDX_shipments_orderId"`);
    await queryRunner.query(`DROP TABLE "shipments"`);
  }
}
