/**
 * Unfilterable Offer Lifecycle Exception
 *
 * Raised when a lifecycle bucket cannot be expressed as a WHERE predicate over
 * the closed `OfferSnapshotFacts` pair (#2026).
 *
 * The lifecycle filter is GENERATED by running the TypeScript rule over that
 * fact space, so a bucket keyed on anything else - variant staleness, snapshot
 * age, a creation-record field - yields no facts. Without this exception the
 * empty result is indistinguishable from `Unsynced`'s legitimately-empty fact
 * set, and the operator would silently be served the wrong page with no error
 * and no failing type-check. Failing loudly on the first request is the point.
 *
 * @module domain/exceptions
 */
export class UnfilterableOfferLifecycleException extends Error {
  constructor(public readonly lifecycle: string) {
    super(
      `Lifecycle bucket "${lifecycle}" cannot be filtered from snapshot facts alone. ` +
        'It resolved to no fact combination, and only `Unsynced` is allowed to do that ' +
        '(it is the absence of the snapshot join). A bucket keyed on anything outside ' +
        '`OfferSnapshotFacts` needs its own predicate in `applyLifecycleFilter`.'
    );
    this.name = 'UnfilterableOfferLifecycleException';
    Error.captureStackTrace(this, this.constructor);
  }
}
