/**
 * Shipment Status Types
 *
 * Persistent shipment lifecycle vocabulary. Used by `Shipment.status` and
 * by `TrackingSnapshot.status` at the port boundary.
 *
 * Notes:
 * - `none` from the #727 product spec AC-3 is a UI-only state — it's
 *   computed from "no row exists" on the order, not persisted.
 * - Pre-provider state is `draft` (not `pending`) because `pending` is
 *   overloaded in OL (sync-jobs use it for "queued for worker",
 *   offer-creation for "awaiting marketplace").
 * - Append-only multiplicity: 1 order → N shipments over time. The AC-7
 *   cancel-and-re-issue path flips the existing row to `cancelled` and
 *   inserts a new row for the re-issue.
 *
 * @module libs/core/src/shipping/domain/types
 */

/**
 * Persisted lifecycle status for a Shipment.
 *
 * - `draft`: row created, label not yet generated by provider.
 * - `generated`: label PDF returned by provider, awaiting dispatch.
 * - `dispatched`: courier picked up.
 * - `in-transit`: first scan after dispatch.
 * - `delivered`: terminal success.
 * - `failed`: terminal failure (label-gen rejection, courier-side error).
 * - `cancelled`: operator-cancelled (AC-7 cancel + re-issue path); terminal.
 */
export const ShipmentStatusValues = [
  'draft',
  'generated',
  'dispatched',
  'in-transit',
  'delivered',
  'failed',
  'cancelled',
] as const;

export type ShipmentStatus = (typeof ShipmentStatusValues)[number];

/**
 * Named-constant map for the shipment lifecycle status. Lets call sites
 * reference status values by name (`SHIPMENT_STATUS.Delivered`) rather
 * than repeating bare string literals. Mirrors the `BULK_BATCH_STATUS`
 * shape in `bulk-offer-creation-batch.types.ts`.
 */
export const SHIPMENT_STATUS = {
  Draft: 'draft',
  Generated: 'generated',
  Dispatched: 'dispatched',
  InTransit: 'in-transit',
  Delivered: 'delivered',
  Failed: 'failed',
  Cancelled: 'cancelled',
} as const satisfies Record<
  'Draft' | 'Generated' | 'Dispatched' | 'InTransit' | 'Delivered' | 'Failed' | 'Cancelled',
  ShipmentStatus
>;

/**
 * Terminal statuses — shipments in these states cannot transition further.
 * Used by `ShipmentRepositoryPort.findActiveByOrderId` to exclude rows
 * from the "current active shipment" lookup.
 */
export const TerminalShipmentStatusValues = ['delivered', 'failed', 'cancelled'] as const;
export type TerminalShipmentStatus = (typeof TerminalShipmentStatusValues)[number];
