/**
 * Offer Mapping Domain Entity
 *
 * Domain entity representing a mapping between a marketplace offer and an
 * internal OpenLinker product. This is a value object/aggregate root for
 * the listings bounded context.
 *
 * @module libs/core/src/listings/domain/entities
 */
export class OfferMapping {
  constructor(
    public readonly id: string,
    public readonly connectionId: string,
    public readonly platformType: string,
    public readonly offerId: string,
    public readonly internalProductId: string,
    public readonly variantId: string | null,
    public readonly createdAt: Date,
    public readonly updatedAt: Date,
  ) {}

  /**
   * Create a new offer mapping
   */
  static create(
    connectionId: string,
    platformType: string,
    offerId: string,
    internalProductId: string,
    variantId?: string | null,
  ): OfferMapping {
    const now = new Date();
    return new OfferMapping(
      '', // ID will be generated by repository
      connectionId,
      platformType,
      offerId,
      internalProductId,
      variantId || null,
      now,
      now,
    );
  }
}


